### PR TITLE
Add bm_6 input, which is 8kx8k version of bm_5 input.

### PR DESCRIPTION
**Pull request by tomdeakin**
Solution value computed in serial on Broadwell, using the Cray compiler.

### CODE REVIEW

**Comment by douglas-shanks** [comment]
The output file tea_bm_6.out is for the 4kx4k problem. Do you have the original output for your run on the Broadwell with the Cray compiler?

**Comment by tomdeakin** [comment]
I've uploaded the output, but the answer is showing `NOT PASSED`. I generated the answer in `field_summary.f90` by running the input on one core. Is it usual to see this much variation? How did the other `bm_*` answers get generated?

**Comment by douglas-shanks** [comment]
For bm_[1,2,3,4] the answers were generated using 1 core. For bm_5 the answer was generated using 24 cores (on a Haswell). I'll do some runs on a Broadwell and see how my answer for `temp` in `field_summary.f90` compares with yours.

**Comment by douglas-shanks** [comment]
Sorry I didn't answer your question on the variation. I haven't looked at the variation for the bm_5 benchmark. I'm assuming that when they wrote the benchmarks they made the assumption that it would be run on a minimum of one node. 

I guess one should expect some variation comparing the value of `temp` from 1 to 36 cores. It's computed by doing a reduction, so the parallel reduction (conceivably changing the order of the summation) would produce a slightly different answer to the serial one.

I think for `qa_diff` it would probably make most sense to use the value of `temp` computed with 36 cores as the comparison value.

**Pull request merged**
